T: 10
surrogate: sigmoid
arch: VGG
num_layers: 8
light_classifier: True

dataset: CIFAR10DVS
data_path: /home/data10T/data/public/cifar10dvs/cifar10_dvs
output_dir: /home/data10T/lpy/neuroai-proj

epochs: 300
batch_size: 128
learning_rate: 0.1
optimizer: SGD
momentum: 0.9
weight_decay: 0.0001
scheduler: CosALR
loss: CE