T: 4
surrogate: sigmoid
arch: ResNet
num_layers: 34
light_classifier: True

dataset: CIFAR10
data_path: /home/lpy/datasets/cifar10
output_dir: /home/data10T/lpy/neuroai-proj

epochs: 300
batch_size: 128
learning_rate: 0.1
optimizer: SGD
momentum: 0.9
weight_decay: 0.0001
scheduler: CosALR
loss: CE